services:
  postgres:
    image: postgres:15
    container_name: kanban-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kanban
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kanban-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kanban-api
    container_name: kanban-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Host=postgres;Database=kanban;Username=kanban;Password=kanban"
    ports:
      - "5000:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
