services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:8080"  # Map host port 5003 to container port 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5433;Database=kanban;Username=kanban;Password=kanban123
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: kanban
      POSTGRES_PASSWORD: kanban123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: